language: php
php:
  - 7.0
install:
  - cp config.sample.php config.php
  - sed -i 's/root/travis/g' config.php
  - sed -i 's/secret//g' config.php
  - sed -i 's/false/true/g' config.php
  - sed -i 's/root/travis/g' codeception.yml
  - sed -i "s/'password'//g" codeception.yml
  - sed -i 's/192.168.99.100/127.0.0.1/g' codeception.yml
  - composer install --dev
  - mysql -e 'CREATE DATABASE machdas;'
  - php vendor/bin/phinx migrate -e dev
  - php vendor/bin/codecept build
  - php -S localhost:9000 -t ./public &
script:
  - node_modules/.bin/eslint frontend/
  - php vendor/bin/codecept run --debug